### ISSUE TITLE
Error Unit test when updating Angular version to 8.x

### ISSUE THREAD

**Issue by ferney1123** [mattlewis92/angular-calendar#1117]
**Describe the bug**

I have been working with angular-calendar v0.26.6 and Angular v7.2.3, but when I try to update the Angular to the 8.x version I'm having trouble with the Unit Test, It seems that the DateAdapter is
not loading, this is the trace:
```
TypeError: Cannot read property 'startOfWeek' of undefined
            at getWeekViewHeader (http://localhost:9876/_karma_webpack_/node_modules/calendar-utils/calendar-utils.js:176:1)
            at CustomCalendarUtils.getWeekViewHeader (http://localhost:9876/_karma_webpack_/node_modules/angular-calendar/fesm2015/angular-calendar.js:1554:33)
            at CalendarMonthViewComponent.refreshHeader (http://localhost:9876/_karma_webpack_/node_modules/angular-calendar/fesm2015/angular-calendar.js:2318:1)
            at CalendarMonthViewComponent.ngOnChanges (http://localhost:9876/_karma_webpack_/node_modules/angular-calendar/fesm2015/angular-calendar.js:2231:1)
            at checkAndUpdateDirectiveInline (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:31905:1)
            at checkAndUpdateNodeInline (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:44366:1)
            at checkAndUpdateNode (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:44305:1)
            at debugCheckAndUpdateNode (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:45327:36)
            at debugCheckDirectivesFn (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:45270:1)
            at Object.eval [as updateDirectives] (ng:///DynamicTestModule/SchedulerCalendarComponent.ngfactory.js:475:9)
I have tried to update the angular-calendar version but It doesn't work
```

This is my TestBed configuration:
```

import { async, ComponentFixture, TestBed } from '@angular/core/testing';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { SchedulerCalendarComponent } from './scheduler-calendar.component';
import * as moment from 'moment';
import {
  CalendarModule,
  DateAdapter as CalendarDateAdapter,
  CalendarMonthViewBeforeRenderEvent,
  CalendarView,
  MOMENT,
  CalendarDateFormatter,
  CalendarMomentDateFormatter,
  DateAdapter,
  CalendarUtils} from 'angular-calendar';
import { format, addDays, getMonth } from 'date-fns';
import { adapterFactory } from 'angular-calendar/date-adapters/moment';
import { TranslateModule, TranslateService } from '@ngx-translate/core';
import { HttpClientModule } from '@angular/common/http';
import { MatDialogModule, MAT_DIALOG_DATA, MatButtonModule } from '@angular/material/';
import { MatDialogRef } from '@angular/material/dialog';
import { MatInputModule } from '@angular/material/input';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { MatSnackBar } from '@angular/material/snack-bar';
import { CustomCalendarUtils } from './custom-calendar-utils';

export function momentAdapterFactory() {
  return adapterFactory(moment);
}

TestBed.configureTestingModule({
      schemas: [
        CUSTOM_ELEMENTS_SCHEMA
      ],
      declarations: [SchedulerCalendarComponent],
      imports: [
        BrowserAnimationsModule,
        CalendarModule.forRoot({
          provide: CalendarDateAdapter,
          useFactory: momentAdapterFactory
        },
        {
          dateFormatter: {
            provide: CalendarDateFormatter,
            useClass: CalendarMomentDateFormatter
          },
          utils: {
            provide: CalendarUtils,
            useFactory: CustomCalendarUtils
          }
        }),
        TranslateModule.forRoot(),
        RouterTestingModule,
        HttpClientModule,
        MatDialogModule,
        CommonModule,
        MatButtonModule,
        MatInputModule,
        FormsModule,
        ReactiveFormsModule
      ],
      providers: [
        TranslateService,
        { provide: MatDialogRef, useValue: matDialogRefStub },
        { provide: MAT_DIALOG_DATA, useValue: {} },
        { provide: MatSnackBar, useValue: matSnackBarStub },
        { provide: MOMENT, useValue: moment }
      ]
    })
      .compileComponents();
```
What can I do to solve this?

**Versions**

- `@angular/core`: 8.2.11
- `angular-calendar`: 0.27.20
- Browser name and version: Google Chrome v77.0.3865.90

**Comment by mattlewis92** [comment]
Hey there, unfortunately I can't really tell what's going on just from the info you posted, any chance you could put together a minimal, runnable repro on github that reproduces your problem? Thanks! 😄
