### ISSUE TITLE
Some times calendar events are non-draggable after scrolling the window

### ISSUE THREAD

**Issue by KirillTovpinets** [mattlewis92/angular-calendar#1251]
Hi.
I faced a bug with dragging calendar events.

**Describe the bug**
When the user add some events on calendar on week view and then scroll the window down and than scroll top, all the events on the calendar become non-draggable at all.

**Minimal reproduction of the problem with instructions**
To reproduce this bug, you should add some events on the week view calendar and then scroll the window down and up. After that, events become non-draggable

**Screenshots**
Here is a video how to reproduce the bug
https://monosnap.com/file/j2XRjh3dWvmxodqLgHqCf3d1WMaInz

**Versions**

- `@angular/core`: 8.2.6
- `angular-calendar`: 0.28.2
- Browser name and version: Chrome 81

**Comment by mattlewis92** [comment]
Hey there, sorry to hear you're experiencing issues, please could you try upgrading to the latest version (`0.28.13`) as there have been a lot of fixes done around drag and drop in the last few versions. If you're still having troubles can you make a minimal repro on stackblitz or something that shows your problem. Thank you! 😄

**Comment by KirillTovpinets** [comment]
@mattlewis92, yea, all works now as expected, thank you. But unfortunately my `ng build` crashed with this errors.
```
ERROR in ./node_modules/angular-calendar/fesm2015/angular-calendar.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:230:35)
    at checkNodeForDecorators (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:53:21)
    at visitNodes (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16631:30)
    at Object.forEachChild (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16859:24)
    at transformer (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:39:16)
    at transformSourceFileOrBundle (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:67384:57)
    at transformation (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:83586:24)
    at transformRoot (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:83606:82)
    at Object.map (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:499:29)
    at Object.transformNodes (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:83593:30)
    at emitJsFileOrBundle (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:84089:32)
    at emitSourceFileOrBundle (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:84043:13)
    at forEachEmittedFile (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:83832:34)
    at Object.emitFiles (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:84026:9)
    at emitWorker (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:89951:33)
    at D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:89912:66
    at runWithCancellationToken (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:90002:24)
    at Object.emit (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:89912:20)
    at Object.transformJavascript (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\src\helpers\transform-javascript.js:111:13)
    at Object.buildOptimizer (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\src\build-optimizer\build-optimizer.js:119:35)
    at Object.buildOptimizerLoader (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\src\build-optimizer\webpack-loader.js:40:40)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tempero.client.app@0.0.0 build-app: `ng build --configuration=production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tempero.client.app@0.0.0 build-app script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\TovpinetsKA\AppData\Roaming\npm-cache\_logs\2020-05-07T13_06_37_587Z-debug.log
```

Here is my versions:

- "@angular/animations": "8.2.6", 
- "@angular/cdk": "^7.3.3", 
- "@angular/core": "8.2.6",

**Comment by KirillTovpinets** [comment]
Oh, I've just update @angular-devkit to 0.803.26 and this solved the problem. Thank you very much for help!

**Comment by mattlewis92** [comment]
Awesome, that's great to hear! 😄

**Comment by shalini-github** [comment]
what is the solution for this. i do not want to update latest version
