### ISSUE TITLE
ionic build --prod generates an error

### ISSUE THREAD

**Issue by EnricoPicci** [mattlewis92/angular-calendar#146]
### Bug description / Feature request:
I have built an app with Ionic2 and angular-calendar.
The project is built and runs correctly the the built is performed with the command `ionic build`.
When I want to make a production build though, with `ionic build --prod`, I get the following error (on the terminal window from which I have launched the build)

```
> ionic-app-scripts build "--prod"

[18:59:40]  ionic-app-scripts 1.1.0 
[18:59:40]  build prod started ... 
[18:59:40]  clean started ... 
[18:59:40]  clean finished in 3 ms 
[18:59:40]  copy started ... 
[18:59:40]  ngc started ... 
can't resolve module ./components/day/calendarDayView.component from /Users/penrico/ThoughWorks/code/angular/castella/node_modules/angular-calendar/dist/esm/src/calendar.module.d.ts
[18:59:42]  build prod failed: Cannot read property 'CalendarDayViewComponent' of undefined, resolving symbol 
            CalendarModule in 
            /Users/penrico/ThoughWorks/code/angular/castella/node_modules/angular-calendar/dist/esm/src/calendar.module.d.ts,
            resolving symbol CalendarModule in 
            /Users/penrico/ThoughWorks/code/angular/castella/node_modules/angular-calendar/dist/esm/src/calendar.module.d.ts
[18:59:42]  ionic-app-script task: "build" 
[18:59:42]  Error: Cannot read property 'CalendarDayViewComponent' of undefined, resolving symbol CalendarModule in 
            /Users/penrico/ThoughWorks/code/angular/castella/node_modules/angular-calendar/dist/esm/src/calendar.module.d.ts,
            resolving symbol CalendarModule in 
            /Users/penrico/ThoughWorks/code/angular/castella/node_modules/angular-calendar/dist/esm/src/calendar.module.d.ts
Error: Cannot read property 'CalendarDayViewComponent' of undefined, resolving symbol CalendarModule in /Users/penrico/ThoughWorks/code/angular/castella/node_modules/angular-calendar/dist/esm/src/calendar.module.d.ts, resolving symbol CalendarModule in /Users/penrico/ThoughWorks/code/angular/castella/node_modules/angular-calendar/dist/esm/src/calendar.module.d.ts
    at simplifyInContext (/Users/penrico/ThoughWorks/code/angular/castella/node_modules/@angular/compiler-cli/src/static_reflector.js:475:23)
    at StaticReflector.simplify (/Users/penrico/ThoughWorks/code/angular/castella/node_modules/@angular/compiler-cli/src/static_reflector.js:478:22)
    at StaticReflector.annotations (/Users/penrico/ThoughWorks/code/angular/castella/node_modules/@angular/compiler-cli/src/static_reflector.js:60:36)
    at NgModuleResolver.resolve (/Users/penrico/ThoughWorks/code/angular/castella/node_modules/@angular/compiler/bundles/compiler.umd.js:14261:46)
    at CompileMetadataResolver._loadNgModuleMetadata (/Users/penrico/ThoughWorks/code/angular/castella/node_modules/@angular/compiler/bundles/compiler.umd.js:14646:45)
    at CompileMetadataResolver.getUnloadedNgModuleMetadata (/Users/penrico/ThoughWorks/code/angular/castella/node_modules/@angular/compiler/bundles/compiler.umd.js:14636:23)
    at addNgModule (/Users/penrico/ThoughWorks/code/angular/castella/node_modules/@angular/compiler/bundles/compiler.umd.js:12944:43)
    at /Users/penrico/ThoughWorks/code/angular/castella/node_modules/@angular/compiler/bundles/compiler.umd.js:12957:16
    at Array.forEach (native)
    at _createNgModules (/Users/penrico/ThoughWorks/code/angular/castella/node_modules/@angular/compiler/bundles/compiler.umd.js:12956:28)

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ionic:build" "--" "--prod"
npm ERR! node v7.4.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ ionic:build: `ionic-app-scripts build "--prod"`
npm ERR! Exit status 1

```

This is the package.json

```
{
  "name": "ionic-hello-world",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic/storage": "1.1.7",
    "angular-calendar": "^0.7.2",
    "angularfire2": "2.0.0-beta.6",
    "firebase": "^3.6.4",
    "intl": "^1.2.4",
    "ionic-angular": "2.0.1",
    "ionic-native": "2.4.1",
    "ng2-responsive": "^0.6.6",
    "rxjs": "5.0.0-beta.12",
    "sw-toolbox": "3.4.0",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.1.0",
    "typescript": "2.0.9"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-statusbar",
    "cordova-plugin-console",
    "cordova-plugin-device",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [
    "ios",
    {
      "platform": "ios",
      "version": "",
      "locator": "ios"
    }
  ],
  "description": "castellammare: An Ionic project"
}
```

### Versions

Angular: 2.2.1

Calendar library: 0.7.2

Browser name and version:

**Comment by mattlewis92** [comment]
It's a bug caused by ionic using an older version of angular, you can fix it by upgrading angular. More info here: https://github.com/driftyco/ionic-app-scripts/issues/550#issuecomment-280785017

**Comment by EnricoPicci** [comment]
Incredibly fast
I will try
Thanks in the meatime

**Comment by EnricoPicci** [comment]
Could you just send me the package.json you are using to fix the problem (I just installed angular2.4.5 but something else now breaks).
Thanks

**Comment by mattlewis92** [comment]
I don't actually use ionic2 myself, that last comment infers they'll be adding official support for the latest angular version next week sometime so I'd suggest waiting until then.

**Comment by EnricoPicci** [comment]
thx
