### ISSUE TITLE
Bug when clicking several days then clicking next or prev month button

### ISSUE THREAD

**Issue by bionets** [mattlewis92/angular-calendar#192]
So i've been playing with my app using angular-calendar using the following versions:

`"@angular/core": "2.4.1",
"angular-calendar": "0.9.1",
"angular-draggable-droppable": "0.5.0"`

Here's my code:
`<div mwlCalendarPreviousView view="month" [(viewDate)]="viewDate" class="btn btn-primary"><i class="fa fa-angle-left"></i></div>`
`<div mwlCalendarNextView view="month" [(viewDate)]="viewDate" class="btn btn-primary"><i class="fa fa-angle-right"></i></div>`
`<mwl-calendar-month-view
                               [events]="events"
                               [viewDate]="viewDate"
                               [dayModifier]="selectedDay"
                               (dayClicked)="onDateSelect($event)"></mwl-calendar-month-view>`

Here's how to replicate the error, click on several dates then click on either previous or next month then you'll get the error below:

TypeError: _this.dayModifier is not a function↵   

 at http://localhost:61543/dist/4.chunk.js:31496:66↵    at Array.forEach (native)↵    at CalendarMonthViewComponent.refreshBody (http://localhost:61543/dist/4.chunk.js:31496:28)↵    at CalendarMonthViewComponent.ngOnChanges (http://localhost:61543/dist/4.chunk.js:31438:18)↵    at Wrapper_CalendarMonthViewComponent.ngDoCheck (/CalendarModule/CalendarMonthViewComponent/wrapper.ngfactory.js:144:20)↵    at CompiledTemplate.proxyViewClass.View_BookingTabComponent0.detectChangesInternal (/BookingModule/BookingTabComponent/component.ngfactory.js:991:42)↵    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:61543/dist/vendor.bundle.js:104348:14)↵    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:61543/dist/vendor.bundle.js:104543:44)↵    at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (http://localhost:61543/dist/vendor.bundle.js:104333:18)↵

Hope you can help me, thanks!

### Versions

Angular: 

Calendar library: 

Browser name and version:

**Comment by mattlewis92** [comment]
Without a plunker it's impossible to say for sure, but from the error that's thrown the value you're passing to `[dayModifier]="selectedDay"` is not a function. Make sure the type of `selectedDay` in your component is a function and it should work ok. Hope that helps! 😄
