### ISSUE TITLE
Error en angular calendar en producción

### ISSUE THREAD

**Issue by hmolinatd** [mattlewis92/angular-calendar#618]
**Describe the bug**

**Minimal reproduction of the problem with instructions**

Please help!
the error occurs after mounting the calendar in production.
**Running:** run ng build --prod
**result 1:**

ERROR in chunk main [initial]
[name].[chunkhash:20].bundle.js
Cannot read property 'range' of null
TypeError: Cannot read property 'range' of null
    at enterNode (D:\desarrollo\Admcamb\admiprod\node_modules\webpack\lib\optimize\ConcatenatedModule.js:145:15)
    at getPathInAst (D:\desarrollo\Admcamb\admiprod\node_modules\webpack\lib\optimize\ConcatenatedModule.js:124:24)
    at getPathInAst (D:\desarrollo\Admcamb\admiprod\node_modules\webpack\lib\optimize\ConcatenatedModule.js:133:24)
    at enterNode (D:\desarrollo\Admcamb\admiprod\node_modules\webpack\lib\optimize\ConcatenatedModule.js:148:18)
    at getPathInAst (D:\desarrollo\Admcamb\admiprod\node_modules\webpack\lib\optimize\ConcatenatedModule.js:137:25)
    at enterNode (D:\desarrollo\Admcamb\admiprod\node_modules\webpack\lib\optimize\ConcatenatedModule.js:148:18)
    at getPathInAst (D:\desarrollo\Admcamb\admiprod\node_modules\webpack\lib\optimize\ConcatenatedModule.js:124:24)
    at getPathInAst (D:\desarrollo\Admcamb\admiprod\node_modules\webpack\lib\optimize\ConcatenatedModule.js:133:24)
    at enterNode (D:\desarrollo\Admcamb\admiprod\node_modules\webpack\lib\optimize\ConcatenatedModule.js:148:18)
    at getPathInAst (D:\desarrollo\Admcamb\admiprod\node_modules\webpack\lib\optimize\ConcatenatedModule.js:124:24)
    at getPathInAst (D:\desarrollo\Admcamb\admiprod\node_modules\webpack\lib\optimize\ConcatenatedModule.js:133:24)
    at info.moduleScope.variables.forEach.variable (D:\desarrollo\Admcamb\admiprod\node_modules\webpack\lib\optimize\ConcatenatedModule.js:526:23)
    at Array.forEach (<anonymous>)
    at modulesWithInfo.forEach.info (D:\desarrollo\Admcamb\admiprod\node_modules\webpack\lib\optimize\ConcatenatedModule.js:514:34)
    at Array.forEach (<anonymous>)
    at ConcatenatedModule.source (D:\desarrollo\Admcamb\admiprod\node_modules\webpack\lib\optimize\ConcatenatedModule.js:506:19)

**running:** run ng build --prod -vc = true
**result 2:** successful compilation.

good to mount the result 2, I see the following. which is shown in the photo.

**Screenshots**
![image](https://user-images.githubusercontent.com/40615383/41944987-c94c66b6-7978-11e8-8b77-9f9f60566161.png)

**Versions**

Angular CLI: 1.5.0
Node: 8.11.1
OS: win32 x64
Angular: 5.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.6.5
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.17
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.8.1

**Comment by mattlewis92** [comment]
It sounds like you're on a newer version of the calendar that doesn't support angular v5, please make sure you're on 0.24.x:
```
npm i angular-calendar@0.24.1
```

If you're still getting stuck, please provide a minimal runnable repo on github that reproduces the issue and I'd be happy to debug more! 😄
